# QUESTION NO1:Convert a 1D array to a 2D array with 2 rows?Desired output::array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]) 

In [4]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr.reshape(2,1,5)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [10]:
np.ndim(arr)

1

# QUESTION NO2:How to stack two arrays vertically?Desired Output::array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [77]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])

In [78]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [80]:
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# QUESTION NO3:How to stack two arrays horizontally?Desired Output::array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [83]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])

In [85]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# QUESTION NO4:How to convert an array of arrays into a flat 1d array?Desired Output::array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
np.ndim(arr)

2

In [62]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# QUESTION NO5:How to Convert higher dimension into one dimension?Desired Output::array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [64]:
arr=np.array([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]])
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [65]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# QUESTION NO6:Convert one dimension to higher dimension?Desired Output::array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [56]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr.reshape(5,1,3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

# QUESTION NO7:Create 5x5 an array and find the square of an array?

In [113]:
arr=5*np.ones([5,5])

In [114]:
arr=arr.astype(np.int32)

In [115]:
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [116]:
np.sqrt(arr)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798]])

# QUESTION NO8:Create 5x6 an array and find the mean?

In [117]:
arr=10*np.ones([5,6])

In [119]:
arr=arr.astype(np.int32)

In [120]:
arr

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [122]:
np.mean(arr)

10.0

# QUESTION NO9:Find the standard deviation of the previous array in Q8?

In [123]:
np.std(arr)

0.0

# QUESTION NO10:Find the median of the previous array in Q8?

In [124]:
np.median(arr)

10.0

# QUESTION NO11:Find the transpose of the previous array in Q8?

In [125]:
np.transpose(arr)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# QUESTION NO12:Create a 4x4 an array and find the sum of diagonal elements?

In [66]:
arr = 10*np.ones([4,4])

In [67]:
arr=arr.astype(np.int32)

In [68]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [69]:
np.diag(arr)

array([10, 10, 10, 10])

# QUESTION NO13:Find the determinant of the previous array in Q12?

In [74]:
arr=10*np.ones([4,4])
arr=arr.astype(np.int32)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [76]:
np.linalg.det(arr)

0.0

# QUESTION NO14:Find the 5th and 95th percentile of an array?

In [78]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
print(np.percentile(a,5))
print(np.percentile(a,95))

1.4500000000000002
9.549999999999999


# QUESTION NO15:How to find if a given array has any null values?

In [2]:
import numpy as np
arr = np.array([0,0,0,0,0,0,0,0])
arr

array([0, 0, 0, 0, 0, 0, 0, 0])