# Beginner level

# QUESTION NO 1: Import the numpy package under the name np

In [2]:
import numpy as np

# QUESTION NO 2 :Create a null vector of size 10

In [24]:
b = np.array([0,0,0,0,0,0,0,0,0,0])
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.size(b)

10

# QUESTION NO 3 :Create a vector with values ranging from 10 to 49

In [4]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# QUESTION NO 4 : Find the shape of previous array in question 3

In [28]:
np.shape(c)

(40,)

# QUESTION NO 5 :Print the type of the previous array in question 3

In [30]:
print(type(c))

<class 'numpy.ndarray'>


# QUESTION NO 6: Print the numpy version and the configuration

In [105]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from 'D:\\ja\\lib\\site-packages\\numpy\\version.py'>
<function show at 0x0000000005376F78>


# QUESTION NO 7 : Print the dimension of the array in question 3

In [5]:
np.ndim(c)

1

# QUESTION NO 8 : Create a boolean array with all the True values

In [76]:
d = np.array([1,2,3,4])
d

array([1, 2, 3, 4])

In [77]:
d>0

array([ True,  True,  True,  True])

# QUESTION NO 9 : Create a two dimensional array

In [65]:
e = np.array([[1,2,3,4,5],[6,7,8,9,10]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
e.ndim

2

# QUESTION NO 10 : Create a three dimensional array

In [67]:
f = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
f

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [68]:
f.ndim

3

# Easy level

# QUESTION NO 11:Reverse a vector (first element becomes last)

In [101]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np
a=np.arange(10,0,-1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# QUESTION NO 12:Create a null vector of size 10 but the fifth value which is 1

In [7]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.size(a)

10

In [10]:
a[5]=1

In [11]:
a

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

# QUESTION NO 13:Create a 3x3 identity matrix

In [104]:
a = np.array([[[1,1,1],[1,1,1],[1,1,1]]])

In [105]:
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

# QUESTION NO 14: arr = np.array([1, 2, 3, 4, 5]) Convert the data type of the given array from int to float

In [106]:
arr = np.array([1,2,3,4,5])
float_number = arr.astype(np.float64)
float_number

array([1., 2., 3., 4., 5.])

# QUESTION NO 15:arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]) Multiply arr1 with arr2

In [91]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [92]:
arr3=arr1*arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# QUESTION NO 16:arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])Make an array by comparing both the arrays provided above

In [107]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

In [108]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [109]:
arr1<arr2

array([[False,  True, False],
       [ True, False,  True]])

# QUESTION NO 17:Extract all odd numbers from arr with values(0-9)

In [31]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

# QUESTION NO 18:Replace all odd numbers to -1 from previous array

In [32]:
np.where(a>=0,-1,1)

array([-1, -1, -1, -1, -1])

# QUESTION NO 19:arr = np.arange(10) Replace the values of indexes 5,6,7 and 8 to 12

In [18]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

# QUESTION NO20:Create a 2d array with 1 on the border and 0 inside

In [117]:
arr2d=np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])
arr2d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [118]:
arr2d[1:-1,1:-1]=0
arr2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# Medium Level 

# QUESTION NO21:arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])Replace the value 5 to 12

In [39]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0:3]=[[5,6,7],[8,9,10],[11,12,13]]
arr2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

# QUESTION NO22:arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])Convert all the values of 1st array to 64

In [4]:
import numpy as np
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr3d[0]=64

In [10]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# QUESTION NO23: Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [76]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
arr[0:1]

array([[0, 1, 2, 3, 4]])

# QUESTION NO24:Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [85]:
ar2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
ar2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
ar2d[1:2]

array([[5, 6, 7, 8, 9]])

# QUESTION NO25:Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [88]:
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

# QUESTION NO26:Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
array=np.random.randn(10,10)
array

array([[-0.37495544,  0.46552605, -0.32501467, -0.3745911 ,  0.5014183 ,
         0.80353773,  1.58276817, -0.65406931,  0.97946179, -1.07031114],
       [ 0.00912892,  2.75147676, -0.50501851, -1.74176742, -1.33522574,
         0.42263001, -0.04544642, -0.05444906,  0.42615451, -0.49907355],
       [-0.17755329,  0.09592134, -0.90034176, -1.08034828, -0.36706404,
         2.10533922, -1.79940788,  0.65752181, -0.97104344, -0.16709385],
       [-0.7993287 ,  1.32587744,  0.59343801,  0.5052233 ,  1.61212904,
         0.70181622,  1.57464892, -0.82751093,  0.1251971 ,  0.90163191],
       [-1.18032599,  1.26265677, -0.2238931 ,  0.4600883 , -0.77523226,
         0.47623265, -0.44047335, -0.99967439, -0.12713621, -1.70969044],
       [ 1.17059584, -0.5001212 , -1.27395543,  0.29357054,  0.96978752,
         0.52691265, -1.74484579,  0.24106291,  0.22649267, -0.23000602],
       [ 0.07268469, -1.28418686,  0.57282486,  0.31558807, -0.76151574,
         1.18421562,  1.19472196, -0.74640062

In [22]:
np.max(array)

2.7514767557256112

In [23]:
np.min(array)

-1.9308033790879764

# QUESTION NO27:a= np.array([1,2,3,2,3,4,3,4,5,6])np.array([7,2,10,2,7,4,9,4,9,8])Find the common items between a and b

In [1]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [9]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.unique(b)

array([ 2,  4,  7,  8,  9, 10])

In [11]:
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# QUESTION NO28:a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])Find the positions where elements of a and b match

In [114]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [116]:
print(np.where(np.intersect1d(a,b)))

(array([0, 1], dtype=int64),)


# QUESTION NO29:names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)Find all the values from array data where the values from array names are not equal to Will

In [117]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [118]:
data=np.random.randn(7,4)
data

array([[-0.50492022, -1.36307848, -1.67546876, -0.57061281],
       [ 1.30058012, -0.19235672, -0.21949999,  0.36282953],
       [-0.70403223, -0.3286188 , -0.71757295,  0.65315587],
       [-0.9136932 ,  1.02723464,  0.77567654,  0.42719244],
       [-1.72364336, -0.39914677, -1.85436648, -0.11924356],
       [ 0.24181326,  0.61333959,  1.40732421,  1.07642192],
       [-0.35503209, -0.41378537, -0.67564467,  0.70334086]])

In [120]:
np.where(names!="will","true" , "false")

array(['true', 'true', 'false', 'true', 'false', 'true', 'true'],
      dtype='<U5')

# QUESTION NO30:names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)Find all the values from array data where the values from array names are not equal to Will and Joe

In [121]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [122]:
data=np.random.randn(7,4)
data

array([[ 0.37494199, -0.54743939,  1.62097109,  0.29210207],
       [-1.05422276,  0.29016808,  0.15983797, -1.17412137],
       [ 1.04367331, -1.50600365,  1.01661562,  2.05420499],
       [ 1.48795855, -0.78675364,  0.64369171,  0.20015636],
       [-0.85187402, -0.04969237,  0.81560519, -0.05399256],
       [ 0.64525128,  0.3220453 , -0.04445211, -1.75621171],
       [-1.21400905, -1.24153655,  0.74202391, -0.3673652 ]])

In [132]:
np.where(names!="joe","true","false")

array(['true', 'false', 'true', 'true', 'true', 'false', 'false'],
      dtype='<U5')

# Hard Level

# QUESTION NO31:Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [15]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
a=arr.astype(np.float64)

In [16]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [14]:
np.ndim(arr)

2

# QUESTION NO32:Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [69]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [70]:
arr = arr2d.astype(np.float64)

In [71]:
arr2d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

# QUESTION NO33:Swap axes of the array you created in Question 32

In [74]:
np.hstack(arr2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [75]:
np.vstack(arr2d)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# QUESTION NO34: Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
array = np.arange(10)

In [38]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# QUESTION NO35:Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [42]:
arr1d=np.random.randn(12)
arr1d

array([ 1.64308558, -0.33334861,  0.14776926, -0.04253604, -0.41969735,
       -1.20708546,  0.07639363, -0.44812601, -0.30149529,  0.04878246,
       -0.46612657, -1.197065  ])

In [43]:
arr2d=np.random.randn(12)
arr2d

array([-1.38505405e+00,  1.42348749e+00,  1.09084404e+00,  9.86631246e-01,
        1.67225759e-01, -3.01203065e-02,  7.84276716e-01,  9.91622827e-01,
       -7.74109611e-04,  1.15076760e+00,  5.26476152e-01,  8.07233392e-02])

In [44]:
np.max((arr1d,arr2d))

1.6430855801519122

# QUESTION NO36:names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])Find the unique names and sort them out!

In [77]:
names=np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [81]:
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

# QUESTION NO37:a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])From array a remove all items present in array b

In [49]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

In [55]:
np.delete(b,0)

array([6, 7, 8, 9])

# QUESTION NO38:Following is the input NumPy array delete column two and insert following new column in its place.sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])newColumn = numpy.array([[10,10,10]])

In [60]:
sampleArray= np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [67]:
np.delete(sampleArray,2,axis=1)

array([[34, 43],
       [82, 22],
       [53, 94]])

In [68]:
np.insert(sampleArray,2,[10,10,10],axis=1)

array([[34, 43, 10, 73],
       [82, 22, 10, 12],
       [53, 94, 10, 66]])

# QUESTION NO39:x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])Find the dot product of the above two matrix

In [87]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])
y=np.array([[6.,23.],[-1,7.],[8,9]])

In [88]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

# QUESTION NO40:Generate a matrix of 20 random values and find its cumulative sum

In [89]:
arr=np.random.rand(20)

In [90]:
arr

array([0.95744348, 0.34274997, 0.32959825, 0.91092374, 0.28550974,
       0.23081035, 0.38493692, 0.03142075, 0.94941237, 0.37619492,
       0.32825299, 0.18063186, 0.91775696, 0.88119476, 0.36450352,
       0.95168681, 0.0914261 , 0.25171943, 0.6483332 , 0.89211882])

In [91]:
np.cumsum(arr)

array([ 0.95744348,  1.30019344,  1.62979169,  2.54071543,  2.82622517,
        3.05703552,  3.44197244,  3.47339319,  4.42280557,  4.79900049,
        5.12725348,  5.30788534,  6.2256423 ,  7.10683705,  7.47134057,
        8.42302738,  8.51445348,  8.76617292,  9.41450612, 10.30662494])